sudo: required
services: 
  - docker

before_install:
  - docker build -t mandroide/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mandroide/docker-react npm run test
language:
  generic

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: " Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-316372775821"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $ACCESS_KEY
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"